name: PR Label Check

on:
  pull_request_target:
    types: [ opened, labeled, unlabeled, synchronize ]

jobs:
  validate-release-label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Check for required label(s)
        uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          use_regex: true
          labels: "changelog:.*"
          add_comment: true